.TH EMF "1" "December 2014" "emf (latzutils)" "User Commands"
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.SH NAME
emf \- EM Fit for gaussian mixture model
.SH SYNOPSIS
.B emf
\fIepochs\fR \fIdata\fR \fIclusters\fR [\fIlabels\fR [\fIdata\fR \fIn\fR]]
.SH DESCRIPTION
.B emf
\fIepochs\fR \fIdata\fR \fIclusters\fR [\fIlabels\fR [\fIdata\fR \fIn\fR]]
.br
runs the EM (Expectation Maximization) algorithm with a d-dimensional
gaussian mixture model, with full covariance matrices and mutable
mixing ratios, where
.PP
.IP \fIepochs
is the number of iterations of EM to run,
.IP \fIdata
is the file of data to read, consisting of N d-dimensional points,
.IP \fIclusters
 is the file of initial values for the mixture model,
.IP \fIlabels
(optional) is a file to write the probabilities of the datapoints to
following the final EM iteration
.IP \fIdata
(optional) is a file of data to read the datapoints whose
probabilities are to be written to,
.IP \fIn
(optional) is the number of points in that second data file.
.PP
At the end of the run, the final state of the mixture model is written
to standard output.
.PP
To change the dimensionality (D), the number of gaussians in the
mixture (K), or number of points in the dataset EM is used on (D), you
have to recompile the program, thus:
.IP
	gcc \-DD=xxx \-DK=xxx \-DN=xxx \-O2 \-s \-o emf emf.c
.PP
By default full covariance matrices are used, if you want diagonal
ones instead add a \-DDIAGONAL to the compilation.
.PP
All data and initialization files can contain comments, which consist
of a ; to the end of the line.  Such a file looks something like this:
.IP
.nf
	; 121 datapoints, 2 clusters, 2-dimensional.
	; Initial sum of priors 1.
	;;; Epoch 200.
	;; Cluster 0
	; prior
	0.475973
	; mean
	 5 22.2657
	; covariance matrix
	    10 1.42109E-14
	    1.42109E-14 274.821

	;; Cluster 1
	; prior
	0.524027
	; mean
	 5 75.1909
	; covariance matrix
	    10 2.84217E-13
	    2.84217E-13 325.442
.fi
.PP
while a reasonable initialization file before EM had run might look
something like this:
.IP
.nf
	; 2 clusters, 2-dimensional.
	; init file
	;; Cluster 0
	; prior
	0.5
	; mean
	0 0
	; covariance matrix
	 1 0
	 0 1

	;; Cluster 1
	; prior
	0.5
	; mean
	2 3
	; covariance matrix
	 1 0
	 0 1
.fi
.PP
All the comments are just that, of course, so be careful.  (You can
always run emf for 0 epochs to see if it agrees with you about the
semantics of the numbers in your file.)

.SH COMPLEXITY

The updates are O(N K D^2 + K D^3) time, and the program uses
O(N D + K D^2) space.

.SH "BUGS AND POTENTIAL PITFALLS"
If the initialization file is bad obviously you can run into trouble.
E.g., if some datapoint has super low probability so it underflows
really far (this could be fixed if I went to a lot of trouble), or if
one cluster is hugging just one point so EM converges to a singularity
(this problem is inherent to maximum likelihood EM).  So be careful
out there!

.SH AUTHOR
.URL mailto:barak@cs.nuim.ie "Barak A. Pearlmutter"
.br
The
.URL http://github.com/barak/emf "EMF development repository"
is on github.
